### ISSUE TITLE
WA

### ISSUE THREAD

**Issue by AlexeySorokin** [SergeiSolopov/Practicum1#2]
На тесте `ab*a..*a. ababaaa` ошибка. Не закрывайте issue самостоятельно.

**Comment by SergeiSolopov** [comment]
Здравствуйте. Возможно, я неправильно понимаю условие. Правильно ли я
понимаю, что эта строка в обычной записи имеет вид (ab*a)*a? Если это так,
то моя программа выдает 1, и самый длинный префикс этого слова, описываемый
этим выражением, - это а.

С уважением,
Сергей Солопов, студент группы Б05-926

**Comment by AlexeySorokin** [comment]
Алгоритм верный.
